module.exports.printTronairLogo = function(){
 
console.log("\x1b[91m                                      #####.                                   ");
console.log("\x1b[91m                                  ,###########(                                ");
console.log("\x1b[91m                               #########(#########                             ");
console.log("\x1b[91m                           .#########.      (########,                         ");
console.log("\x1b[91m                        ##########              #########                      ");
console.log("\x1b[91m                     #########/                    /########                   ");
console.log("\x1b[91m                 (#########                            ########/               ");
console.log("\x1b[91m              #########(                /.                 /########           "); 
console.log("\x1b[91m          /#########.                #######,                 ########,        ");
console.log("\x1b[91m       ##########                (##############             (###########(     ");
console.log("\x1b[91m      ######\x1b[97m___              \x1b[91m#####################            \x1b[97m_  \x1b[91m##########    ");
console.log("\x1b[91m      #### \x1b[97m/ __\\ ___   _ __ ___   _ __ ___   _   _  _ __  (_)| |_  _   _\x1b[91m ##    ");
console.log("\x1b[91m      ### \x1b[97m/ /   / _ \\ | '_ ` _ \\ | '_ ` _ \\ | | | || '_ \\ | || __|| | | |\x1b[91m##    ");
console.log("\x1b[91m      ## \x1b[97m/ /___| (_) || | | | | || | | | | || |_| || | | || || |_ | |_| |\x1b[91m##    ");
console.log("\x1b[91m      ## \x1b[97m\\____/ \\___/ |_| |_| |_||_| |_| |_| \\__,_||_| |_||_| \\__| \\__, |\x1b[91m##    ");
console.log("\x1b[91m      ###                            ########################      \x1b[97m|___/ \x1b[91m##    ");
console.log("\x1b[91m      #####         #              \x1b[97m_\x1b[91m  ######### \x1b[97m_ \x1b[91m###########           ###    ");
console.log("\x1b[91m      #####         ####.     \x1b[97m /\\ \\ \\ ___    __| |  ___ \x1b[91m#####         #####    ");
console.log("\x1b[91m      #####         #######(  \x1b[97m/  \\/ // _ \\  / _` | / _ \\ \x1b[91m####         #####    ");
console.log("\x1b[91m      #####         ######## \x1b[97m/ /\\  /| (_) || (_| ||  __/ \x1b[91m####         #####    ");
console.log("\x1b[91m      #####         ######## \x1b[97m\\_\\ \\/  \\___/  \\__,_| \\___| \x1b[91m####         #####    ");
console.log("\x1b[91m      #####         #########,                            ###         #####    ");
console.log("\x1b[91m      #####         #####################/                 ##         #####    ");
console.log("\x1b[91m      #####         #########################               #         #####    ");
console.log("\x1b[91m      #####         ############################,                     #####    ");
console.log("\x1b[91m      #####         ################################                  #####    ");
console.log("\x1b[91m      #####            ################################,              #####    ");
console.log("\x1b[91m      #####               .################################           #####    ");
console.log("\x1b[91m      ######                  (###############################.     *######    ");
console.log("\x1b[91m      .#########                  #############      #####################     ");
console.log("\x1b[91m          #########*                 .######            ##############/        ");
console.log("\x1b[91m             .#########                ##                .#########            ");
console.log("\x1b[91m                 (########,                           (########/               ");
console.log("\x1b[91m                    .#########     \x1b[94mtronair-cli\x1b[91m     #########                   ");
console.log("\x1b[91m                        (########,             .########(                      ");
console.log("\x1b[91m                            #########       (########.                         ");
console.log("\x1b[91m                               (########.#########                             ");
console.log("\x1b[91m                                   ###########/                                ");
console.log("\x1b[91m                                      #####.                                   ");
console.log("                               Welcome to TRONAIR-CLI");
console.log("\x1b[91m           The ultimate command line \x1b[94mairdrop\x1b[91m tool for the TRON blockchain");
console.log("\x1b[91m                       Telegram: https://t.me/CommunityNode");
console.log("\x1b[93m                        If you need any help, please type:");
console.log("\x1b[93m                             node index.js  --help\x1b[90m\n");

//process.stdout.write("\x1b[94mLoading interface.. \x1b[91m\r");
//console.log("");
}